#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-glmnet
Version  : 2.0.16
Release  : 54
URL      : https://cran.r-project.org/src/contrib/glmnet_2.0-16.tar.gz
Source0  : https://cran.r-project.org/src/contrib/glmnet_2.0-16.tar.gz
Summary  : Lasso and Elastic-Net Regularized Generalized Linear Models
Group    : Development/Tools
License  : GPL-2.0
Requires: R-glmnet-lib
Requires: R-foreach
BuildRequires : R-foreach
BuildRequires : clr-R-helpers
BuildRequires : gfortran

%description
No detailed description available

%package lib
Summary: lib components for the R-glmnet package.
Group: Libraries

%description lib
lib components for the R-glmnet package.


%prep
%setup -q -c -n glmnet

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522681307

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1522681307
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library glmnet
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library glmnet
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library glmnet
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library glmnet|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/glmnet/CITATION
/usr/lib64/R/library/glmnet/DESCRIPTION
/usr/lib64/R/library/glmnet/INDEX
/usr/lib64/R/library/glmnet/Meta/Rd.rds
/usr/lib64/R/library/glmnet/Meta/data.rds
/usr/lib64/R/library/glmnet/Meta/features.rds
/usr/lib64/R/library/glmnet/Meta/hsearch.rds
/usr/lib64/R/library/glmnet/Meta/links.rds
/usr/lib64/R/library/glmnet/Meta/nsInfo.rds
/usr/lib64/R/library/glmnet/Meta/package.rds
/usr/lib64/R/library/glmnet/Meta/vignette.rds
/usr/lib64/R/library/glmnet/NAMESPACE
/usr/lib64/R/library/glmnet/R/glmnet
/usr/lib64/R/library/glmnet/R/glmnet.rdb
/usr/lib64/R/library/glmnet/R/glmnet.rdx
/usr/lib64/R/library/glmnet/data/BinomialExample.RData
/usr/lib64/R/library/glmnet/data/CVXResults.RData
/usr/lib64/R/library/glmnet/data/CoxExample.RData
/usr/lib64/R/library/glmnet/data/MultiGaussianExample.RData
/usr/lib64/R/library/glmnet/data/MultinomialExample.RData
/usr/lib64/R/library/glmnet/data/PoissonExample.RData
/usr/lib64/R/library/glmnet/data/QuickStartExample.RData
/usr/lib64/R/library/glmnet/data/SparseExample.RData
/usr/lib64/R/library/glmnet/doc/Coxnet.R
/usr/lib64/R/library/glmnet/doc/Coxnet.pdf
/usr/lib64/R/library/glmnet/doc/Coxnet.rnw
/usr/lib64/R/library/glmnet/doc/glmnet_beta.R
/usr/lib64/R/library/glmnet/doc/glmnet_beta.Rmd
/usr/lib64/R/library/glmnet/doc/glmnet_beta.pdf
/usr/lib64/R/library/glmnet/doc/index.html
/usr/lib64/R/library/glmnet/help/AnIndex
/usr/lib64/R/library/glmnet/help/aliases.rds
/usr/lib64/R/library/glmnet/help/glmnet.rdb
/usr/lib64/R/library/glmnet/help/glmnet.rdx
/usr/lib64/R/library/glmnet/help/paths.rds
/usr/lib64/R/library/glmnet/html/00Index.html
/usr/lib64/R/library/glmnet/html/R.css
/usr/lib64/R/library/glmnet/libs/symbols.rds
/usr/lib64/R/library/glmnet/mortran/glmnet5dp.m

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/glmnet/libs/glmnet.so
/usr/lib64/R/library/glmnet/libs/glmnet.so.avx2
/usr/lib64/R/library/glmnet/libs/glmnet.so.avx512
