#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-glmnet
Version  : 1.9
Release  : 13
URL      : http://cran.r-project.org/src/contrib/glmnet_1.9-8.tar.gz
Source0  : http://cran.r-project.org/src/contrib/glmnet_1.9-8.tar.gz
Summary  : and elastic-net regularized generalized linear models
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : clr-R-helpers
BuildRequires : gfortran

%description
No detailed description available

%prep
%setup -q -c -n glmnet

%build

%install
rm -rf %{buildroot}
export LANG=C
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library glmnet
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library glmnet


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/glmnet/CITATION
/usr/lib64/R/library/glmnet/DESCRIPTION
/usr/lib64/R/library/glmnet/INDEX
/usr/lib64/R/library/glmnet/Meta/Rd.rds
/usr/lib64/R/library/glmnet/Meta/hsearch.rds
/usr/lib64/R/library/glmnet/Meta/links.rds
/usr/lib64/R/library/glmnet/Meta/nsInfo.rds
/usr/lib64/R/library/glmnet/Meta/package.rds
/usr/lib64/R/library/glmnet/Meta/vignette.rds
/usr/lib64/R/library/glmnet/NAMESPACE
/usr/lib64/R/library/glmnet/R/glmnet
/usr/lib64/R/library/glmnet/R/glmnet.rdb
/usr/lib64/R/library/glmnet/R/glmnet.rdx
/usr/lib64/R/library/glmnet/doc/Coxnet.R
/usr/lib64/R/library/glmnet/doc/Coxnet.pdf
/usr/lib64/R/library/glmnet/doc/Coxnet.rnw
/usr/lib64/R/library/glmnet/doc/index.html
/usr/lib64/R/library/glmnet/help/AnIndex
/usr/lib64/R/library/glmnet/help/aliases.rds
/usr/lib64/R/library/glmnet/help/glmnet.rdb
/usr/lib64/R/library/glmnet/help/glmnet.rdx
/usr/lib64/R/library/glmnet/help/paths.rds
/usr/lib64/R/library/glmnet/html/00Index.html
/usr/lib64/R/library/glmnet/html/R.css
/usr/lib64/R/library/glmnet/libs/glmnet.so
/usr/lib64/R/library/glmnet/libs/symbols.rds
/usr/lib64/R/library/glmnet/mortran/glmnet5.m
